### ISSUE TITLE
Kostal Piko

### ISSUE THREAD

**Issue by OH6HFX** [robertdiers/solar-manager#1]
Hi! I have tried Kostal.py with PIKO CI inverter, but so far I'm not getting right values from registers. Do you know if there has to be different conversion for PIKO register values than in Plenticore?

**Comment by robertdiers** [comment]
Hi - I do not have a Piko to test it, but it might be the configured value in inverter (big and little-endian should be available). The other option would be to request data from Kostal Smart Meter. Maybe this could help: https://github.com/robertdiers/kostal_idmpump/tree/main/backup

**Comment by robertdiers** [comment]
Here we can find the register of Energy Meter: https://www.kostal-solar-electric.com/en-gb/products/accessories/smart-energy-meter/-/media/document-library-folder---kse/2020/12/15/14/22/ba_kostal_interface_ksem_de.pdf

**Comment by GeorgFreiberger** [comment]
My Piko CI 30 is working with the Plenticore Hybrid template.
Remaining Problem: The Com. Board  ist only supplied via DC Voltage (from the Panels), so after sunset: no Communication.
