### ISSUE TITLE
[Invalid Message] No response received, expected at least 8 bytes (0 received)

### ISSUE THREAD

**Issue by tpd-opitz** [robertdiers/solar-manager#2]
I tried your code but I the function call [client.read_holding_registers(myadr_dec,2,slave=unitid)](https://github.com/robertdiers/solar-manager/blob/0e4f659f9d2f7a9e0e665d4e65cd8741d2bc0f6e/python/Kostal.py#L13) returns an error object rather than any value. When i add `print(f"r1: {r1}")` right behind that line I get:
```
 Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)
```

I checked that Modbus-TCP is active in my inverter. 

Could you please help me tracking that problem down?

**Comment by robertdiers** [comment]
Hey - I think in Inverter u should find an option about the format. Maybe you can try out the other ones ;-)

**Comment by tpd-opitz** [comment]
Using a newer version of pymodbus solved the problem...

BTW: in 3.7.4 the constants in `Endian` are now uppercase...

**Comment by robertdiers** [comment]
Thanks
